name = "GeoBasics"
uuid = "8fb48e0b-3c9c-4361-9123-9e8e6ea58083"
version = "1.2.0"
authors = ["Alberto Mengali <disberd@gmail.com>"]

[deps]
BasicTypes = "13e19751-ccd1-416d-be0c-a6724a8caa31"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
GeoPlottingHelpers = "c20ae07a-79b5-4dbd-b2dc-f2e51386613e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BasicTypes = "2"
CircularArrays = "1"
CoordRefSystems = "0.16 - 0.19"
GeoPlottingHelpers = "0.1.4"
Meshes = "0.51 - 0.55"
Unitful = "1"
julia = "1.11"
